@startuml
' Диаграмма потока данных: Регистрация пациента
left to right direction
title DFD: Регистрация пациента

skinparam rectangle {
  BackgroundColor #FFCCCC
}
skinparam database {
  BackgroundColor #CCE5FF
}

' Участники (человечки)
actor "Пациент" as patient
actor "Администратор\nрегистратуры" as admin

' Хранилища данных (базы данных)
database "список\nпациентов" as patients_db
database "файл с общей\nинформацией\nо пациенте в его МК" as patient_folder

' Процессы (прямоугольники)
rectangle "Поиск пациента\nв базе" as search_process
rectangle "Заполнение\nанкеты" as fill_form
rectangle "Создание\n МК пациента" as create_card
rectangle "Добавление в\nсписок пациентов" as add_new

' Потоки данных
patient --> admin : Паспорт, ФИО,\nконтактные данные
admin --> search_process : Запрос на поиск
search_process <-- patients_db : Скачивание списка перед открытием
admin --> fill_form : Ввод данных пациента
fill_form --> create_card : Данные анкеты
create_card --> patient_folder : Сохранение\nанкеты пациента
fill_form --> add_new : Данные нового пациента
add_new --> patients_db : Добавление пациента в список

@enduml
