@startuml
' Диаграмма потока данных: Приём у врача
left to right direction
title DFD: Приём у врача / прохождение медицинских процедур

skinparam rectangle {
  BackgroundColor #FFCCCC
}
skinparam database {
  BackgroundColor #CCE5FF
}

' Участники (человечки)
actor "Пациент" as patient
actor "Врач" as doctor

' Хранилища данных (базы данных)
database "журнал записей\n(в сетевой папке)" as schedule_db
database "мед. карта\n(сетевая папка)" as med_card

' Процессы (прямоугольники)
rectangle "Отметка о\nприёме" as mark_visit
rectangle "Ведение\nприёма" as conduct_visit
rectangle "Документирование\nрезультатов" as document_results
rectangle "Выписка\nрецепта" as prescription

' Потоки данных
patient --> doctor : Жалобы, симптомы
doctor --> mark_visit : ФИО пациента
mark_visit --> schedule_db : Пометка:\nприём состоялся
doctor --> conduct_visit : Осмотр пациента
conduct_visit --> document_results : Симптомы, диагноз,\nназначения
document_results --> med_card : описание приёма,\nдиагноз, назначения,\nдоп. файлы диагностики (УЗИ, ЭКГ и др.)\n

doctor --> prescription : Назначение\nрецептурных препаратов
prescription --> patient : Лист назначений,\nбумажный рецепт

@enduml
